### ISSUE TITLE
Issue with Flux git password

### ISSUE THREAD

**Issue by rpavez** [aws-samples/aws-cdk-eks-flux#1]
https://github.com/aws-samples/aws-cdk-eks-flux/blob/22285365f277542abf12cbeb7341a62283d134eb/fluxcd/fluxcd_cluster.py#L24

This is failing to properly encode the password.

**Comment by cesarpball** [comment]
Hi @rpavez 

Would you mind to share more details about your error? OS version? CDK version? Python version and libraries? Error message?

**Comment by cesarpball** [comment]
Hi @rpavez ,

I am going to close this issue as I don't have updates since more than 60 days. Please, open a new issue if you are still facing this issue.

Regards
